# 输入和输出

## 1. numpy二进制文件

In [1]:
import numpy as np

In [6]:
outfile = r'.\test.npy'
np.random.seed(20200619)
x = np.random.uniform(0,1,[3,5])
np.save(outfile,x)
y = np.load(outfile)
print(y)

[[0.01123594 0.66790705 0.50212171 0.7230908  0.61668256]
 [0.00668332 0.1234096  0.96092409 0.67925305 0.38596837]
 [0.72342998 0.26258324 0.24318845 0.98795012 0.77370715]]


In [8]:
outfile = r'.\test.npz'
x = np.linspace(0, np.pi, 5)
y = np.sin(x)
z = np.cos(x)
np.savez(outfile, x, y, z_d=z)
data = np.load(outfile)
np.set_printoptions(suppress=True)
print(data.files)  
print(data['arr_0'])
print(data['arr_1'])
print(data['z_d'])

['z_d', 'arr_0', 'arr_1']
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.         0.70710678 1.         0.70710678 0.        ]
[ 1.          0.70710678  0.         -0.70710678 -1.        ]


## 2. 文本文件

In [9]:
import numpy as np

In [10]:
outfile = r'.\test.txt'
x = np.arange(0, 10).reshape(2, -1)
np.savetxt(outfile, x)
y = np.loadtxt(outfile)
print(y)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [11]:
outfile = r'.\test.csv'
x = np.arange(0, 10, 0.5).reshape(4, -1)
np.savetxt(outfile, x, fmt='%.3f', delimiter=',')
y = np.loadtxt(outfile, delimiter=',')
print(y)

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]


In [21]:
print(x.dtype)

float64


In [25]:
print(x['id'])
print(x['value1'])  
print(x['value2'])  
print(x['value3']) 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices